POST http://localhost:5000/signup HTTP/1.1
Content-Type: application/json

{"checkbox1": false,
"displayName": "1111",
"email": "roanhde0v411@gmail.com",
"firstName": "1111",
"lastName": "1111",
"password": "11111",
"passwordConfirm": "11111",
"radio": ""}